feat: support to thirdweb
xpladev/xpla pull request #142
Opened 2024-08-05 09:26 UTC by JoowonYun

## Effects

- [ ] Soft update
- [x] Breaking change
- [ ] Chain fork related

## Major Reviewer
@leeyunseon @yoosah 

## Background

https://github.com/Arachnid/deterministic-deployment-proxy

## Summary

## Checklist

- [ ] Backward compatible?
- [ ] Test enough in your local environment?
- [ ] Add related test cases?

2024-08-05 09:44 UTC, leeyunseon approved these changes

2024-08-05 09:45 UTC, yoosah requested changes

2024-08-05 09:45 UTC, yoosah commented on app/upgrades/v1_6/upgrades.go
> +		print(res.String())
check this

2024-08-06 09:43 UTC, leeyunseon approved these changes

2024-08-06 11:46 UTC, yoosah approved these changes

2024-08-07 02:33 UTC, merged